### ISSUE TITLE
need help by Blender pmo import Pythonscript

### ISSUE THREAD

**Issue by wervgfhjg** [svanheulen/mhff#1]
Linke the title says, i have a probelm with the pmo importer.
It will not import the "001_data.pmo", just the "005_data.pmo" are im portable for my Blender script.

I need the Monsters models, but they are not importable for me.

I am using Blender 2.69 and Python 3.4

Please help me

**Comment by svanheulen** [comment]
Firstly, the all the PMO code in this repository only works with Monster Hunter 3rd files. Secondly the Blender script is buggy and I would recommend using the "pmo.py" file. That will convert a PMO to Wavefront OBJ format, which you can then import into Blender.

**Comment by wervgfhjg** [comment]
The pmo.py is not Wirkung correctly too

I geht an error after using the correct commands

**Comment by svanheulen** [comment]
Please post the error you're getting

**Comment by wervgfhjg** [comment]
Woops.. sorry for doubleposting, but i habe forgot something

The error, that Python gives back, is "acces denied
Erno 13"

**Comment by svanheulen** [comment]
I need the full Python traceback, please.
Also, the full command you're using could be helpful.

**Comment by wervgfhjg** [comment]
One second.. i am on my mobile device right now..

So first i opened the cmd.. than i habe tiped in "CD c:/python33

Now i am in my Python folder
Than i've tiped "Python pmo.py 001_data.pmo Name.mtl output.obj

I think, that was what i have tiped in.

Could we get in contact via Skype or something linke that?

 I am an experienced Modder. Doin that since 6 years.

**Comment by svanheulen** [comment]
You're welcome to email me at the address on my profile here, or I'm available on IRC, freenode.net, using this same screen name.

If you're getting an access denied error, the most likely problem is that you don't have permissions to create files in that directory.

**Comment by wervgfhjg** [comment]
Okay thank you^^

Well.. i have admin rights.. that is strange
Would it help if i reinstall Python into another directory like my desktop?

**Comment by svanheulen** [comment]
Well so long as you have permissions for that directory it shouldn't make a difference, but I guess it wouldn't hurt to try.

**Comment by wervgfhjg** [comment]
Yes, you are right

 Thanks for your fast answers^^

**Comment by svanheulen** [comment]
Actually, which file are you trying to convert? I still have my game around here someplace so I can test it.

**Comment by wervgfhjg** [comment]
I habe tested it with Akantor outta 3rd, Wirth Rathalos outta 3rd and Wirth kut ku outta 2nd g

**Comment by svanheulen** [comment]
Ah ok, yeah, I just tested those and I'm getting errors as well. I know I had it working on those at one point, I'll look through my commits and see if I can figure it out.

**Comment by wervgfhjg** [comment]
Okay, thank you ^^

Do you geht the same error?

**Comment by svanheulen** [comment]
I don't think so. This is the error I'm getting:

```
Traceback (most recent call last):
  File "./pmo.py", line 256, in <module>
    convert_pmo(args.pmofile, args.mtlfile, args.outputfile)
  File "./pmo.py", line 242, in convert_pmo
    convert_mh3_pmo(pmo, obj)
  File "./pmo.py", line 213, in convert_mh3_pmo
    mesh.append(run_ge(pmo, scale) + (material,))
  File "./pmo.py", line 40, in run_ge
    command = array.array('I', pmo.read(4))[0]
IndexError: array index out of range
```

Seems like it's having trouble reading the GE commands.

**Comment by wervgfhjg** [comment]
Ahh.. thats what i am getting too.. 

I had try To edit the pmo.py, afterthat, this error was fixed, but i couldnt accessing it then

**Comment by svanheulen** [comment]
I think I know what the problem is, just need to read over my code... it's been so long since I last used this, haha.

**Comment by wervgfhjg** [comment]
Okay, good luck

 And many thanks for making that circumstances for me^^

**Comment by svanheulen** [comment]
Aha, I figured it out. I forgot that the monster model are different then the armor/weapon models. They're actually split into two files.

So for Rathian, file number 5141 is the package and file 0001 inside that package is the first half of the PMO. The file number 5142 is the second half of the PMO, so you have to combine the two files before the pmo.py will be able to read it.

I only use Linux so I'm not sure how to do that in Windows, maybe a hex editor?

**Comment by wervgfhjg** [comment]
Combining the files?
That sounds strange..

**Comment by svanheulen** [comment]
You just have to concatenate the files.
Here's how to do that in Windows using the `copy` command: http://www.omnicode.com/qa.php?id=35

**Comment by wervgfhjg** [comment]
Thanks a lot! I am going Tod try it

After combining it should work?

**Comment by wervgfhjg** [comment]
Phew.. its a coder language.. 
I am not und er standing it at all..

I am just a modder xD

Wouldnt it possible for you Tod put the codes for Monster Models to your py file?

**Comment by svanheulen** [comment]
Yeah, I can do that. Just give me a few min to make the changes.

**Comment by wervgfhjg** [comment]
Ohh thank you so much!

**Comment by svanheulen** [comment]
Ok, I think that should do it. There's a new command option that lets you specify the second file.

**Comment by wervgfhjg** [comment]
Just Amazing, nice job !

**Comment by svanheulen** [comment]
Glad I could help! If you run into any more problems feel free to email me or open another issue.
