### ISSUE TITLE
Converting a DDS back to TEX

### ISSUE THREAD

**Issue by Chakratos** [svanheulen/mhff#3]
Hey,
just wanted to ask how to convert an DDS back to TEX for MHX.

**Comment by svanheulen** [comment]
I haven't made a tool for that yet. I plan on making one ...but I'm not sure when I'll get around to doing it. Other then recompressing the ETC1 textures, it should be pretty easy to do. If you don't feel like waiting and you're feeling ambitious, check out the wiki for information about the texture file format.

**Comment by aesth0x** [comment]
Hi, just wondering if you are working on converting PNG to TEX. If not, I'll try to code myself; else I'll wait for your tool. Thanks! :D

**Comment by svanheulen** [comment]
I haven't started on it yet so if you can, please do.
