### ISSUE TITLE
Possible bug in n3ds/arc.py

### ISSUE THREAD

**Issue by aesth0x** [svanheulen/mhff#5]
I run arc.py to extract an mhx arc file, and then without modifying it, I compressed the extracted folder into an new arc file. The new arc is different in size with the original arc, which is probably problematic. I replaced the old arc with the new arc and rebuild the rom. Then the corresponding image became gray in the game (which shouldn't change since I didn't modify the arc besides extraction and compression). 
The arc file that I tested is ExtractedRomFS\arc\weapon\w02\057.arc, which corresponds to Shagaru Magala Hammer. 
The commands I run are:
python arc.py x 057.arc
python arc.py c 057.arc weapon

Thank you for looking into this problem!

**Comment by aesth0x** [comment]
Alright, I think the problem is that the order of files in an arc file matters. I make the order of files in the new file the same as the order in the original arc file, it works.

**Comment by mhvuze** [comment]
Yes, the files must be in the exact same order and use the original compression level. Atleast that's what I came to as a conclusion when building my repacking tool last year

**Comment by svanheulen** [comment]
Yeah, the files need to be in the same order. That's why I didn't originally have a recursive option for creating ARCs, but people asked for it so I added it anyway.
Although there will always be a slight difference in size between files made with my tool because the official ARCs have the data aligned in some way after the table of contents. Looking at the game's code though, it doesn't seem to care if it's aligned or not so I don't think it's an issue.

**Comment by aesth0x** [comment]
For arc of monsters, even though I make the order the same as the original arc, the game crashed when loading the monster data at the quest loading scene. Cannot figure out why. 
(The one I tested was em082_00.arc)

**Comment by svanheulen** [comment]
I'll look into it

**Comment by Dappercino** [comment]
Hey there, sorry for bothering you on such an old thread.

I had the idea of using arc.py to unpack and repack a certain quest DLC file from MHXX, and then using your Data Manager to get it back into my game. I know these tools are for MHX/Gen, but I thought to just put this here for if you get back to working on MHXX.

Unpacking works great, but I had the same problem as the guy above where, if I unpack and repack (in the same file order as the original and without editing anything), it fails to run on Local play (works fine in single player), with the game saying "Request failed. Quest data is incorrect". I noticed that the repacked file is lower in size, too.

If you're interested, I uploaded the two .arc files here.
[RomFS.zip](https://github.com/svanheulen/mhff/files/1556098/RomFS.zip)

Thanks for your work!

**Comment by ravenCondol** [comment]
Hello, I used your arc.py to unpack DLC quest files for the creation of custom quests in MHXX.

Upon repacking non-recursively, the game seems to be able to recognize the quest has been edited and gives a "Request failed. Quest data is incorrect" error when choosing the quest from the hub. This happens even if I unpack & repack a legitimate quest .arc file _without any edits_. Can't figure out why, any ideas would be appreciated. 

[quest.zip](https://github.com/svanheulen/mhff/files/1556548/quest.zip)
Attached is the original and repacked (non-edited) version. Thank you for your work!

**Comment by svanheulen** [comment]
I haven't had a chance to look into the issue yet... and I'm not sure if I'll ever get around to it. Sorry.
If anyone figures it out, send me a pull request.
