### ISSUE TITLE
Met some problems when opening .arc

### ISSUE THREAD

**Issue by PhantomGS** [svanheulen/mhff#6]
Hi,master

I decrypted the dlc mission and when i try to modify it problems come out, sorry to bother you again : \

E:\maggi\mhff-master\n3ds>python arc.py x q1010117.arc
extracting: quest\questData\questData_1010117_jpn.gmd, type: rGUIMessage, compressed size: 396, size: 547
Traceback (most recent call last):
  File "arc.py", line 384, in <module>
    extract_arc(args.inputfile, args.outputpath)
  File "arc.py", line 344, in extract_arc
    os.makedirs(os.path.dirname(file_name), exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

E:\maggi\mhff-master\n3ds>
Thank you for your key in mhef, anyway have a good day!

**Comment by svanheulen** [comment]
The `n3ds/arc.py` script is only compatible with Python 3.2+
