### ISSUE TITLE
How do i open mh4u files with blender?

### ISSUE THREAD

**Issue by Heltrato** [svanheulen/mhff#8]
Is this repo still up? im gonna ask how do i import or open the models from 4u from 
this https://www.reddit.com/r/MonsterHunter/comments/511jsk/anyone_in_need_of_mh4u_monster_models_3ds_max_only/?sort=new

**Comment by svanheulen** [comment]
The `io_import_scene_mod.py` is a Blender plugin. You can read how to install plugins in the Blender documentation. That being said, this isn't complete (and probably never will be) so it only really imports the polygons.
